/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KRLMRQZ
 */
public class Calcu extends javax.swing.JFrame {

   
    public Calcu() {
        initComponents();
        this.setSize(613,590);
        this.setLocationRelativeTo(null);
        cashReceived.setEditable(false);
        lblAssign.setVisible(false);
        
        //cashReceived.setText("");
        //customerName.setText("");
    }
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ordering", "root", "");
        }
        
        catch (ClassNotFoundException ex){
            Logger.getLogger(Calcu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Calcu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashReceived = new javax.swing.JTextField();
        lblAssign = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        btnNumber9 = new javax.swing.JButton();
        btnNumber8 = new javax.swing.JButton();
        btnNumber7 = new javax.swing.JButton();
        btnNumber6 = new javax.swing.JButton();
        btnNumber5 = new javax.swing.JButton();
        btnNumber4 = new javax.swing.JButton();
        btnNumber3 = new javax.swing.JButton();
        btnNumber2 = new javax.swing.JButton();
        btnNumber1 = new javax.swing.JButton();
        btnNumber0 = new javax.swing.JButton();
        btnDecimalPt = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        customerName = new javax.swing.JTextField();
        lblPayment1 = new javax.swing.JLabel();
        lblSuntea = new javax.swing.JLabel();
        lblStaMesa = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblSunteaLogo = new javax.swing.JLabel();
        lblYellowBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        cashReceived.setFont(new java.awt.Font("Bahnschrift", 1, 60)); // NOI18N
        cashReceived.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cashReceived.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashReceivedActionPerformed(evt);
            }
        });
        getContentPane().add(cashReceived);
        cashReceived.setBounds(10, 230, 590, 90);

        lblAssign.setText("jLabel1");
        getContentPane().add(lblAssign);
        lblAssign.setBounds(470, 260, 34, 14);

        lblPayment.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 102));
        lblPayment.setText("Input the customer's name.");
        getContentPane().add(lblPayment);
        lblPayment.setBounds(10, 190, 420, 30);

        btnNumber9.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber9.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber9.setText("9");
        btnNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber9);
        btnNumber9.setBounds(410, 360, 190, 40);

        btnNumber8.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber8.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber8.setText("8");
        btnNumber8.setBorderPainted(false);
        btnNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber8);
        btnNumber8.setBounds(210, 360, 190, 40);

        btnNumber7.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber7.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber7.setText("7");
        btnNumber7.setBorder(null);
        btnNumber7.setBorderPainted(false);
        btnNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber7);
        btnNumber7.setBounds(10, 360, 190, 40);

        btnNumber6.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber6.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber6.setText("6");
        btnNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber6);
        btnNumber6.setBounds(410, 410, 190, 40);

        btnNumber5.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber5.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber5.setText("5");
        btnNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber5);
        btnNumber5.setBounds(210, 410, 190, 40);

        btnNumber4.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber4.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber4.setText("4");
        btnNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber4);
        btnNumber4.setBounds(10, 410, 190, 40);

        btnNumber3.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber3.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber3.setText("3");
        btnNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber3);
        btnNumber3.setBounds(410, 460, 190, 40);

        btnNumber2.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber2.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber2.setText("2");
        btnNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber2);
        btnNumber2.setBounds(210, 460, 190, 40);

        btnNumber1.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber1.setText("1");
        btnNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber1);
        btnNumber1.setBounds(10, 460, 190, 40);

        btnNumber0.setBackground(new java.awt.Color(255, 255, 0));
        btnNumber0.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnNumber0.setText("0");
        btnNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber0ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNumber0);
        btnNumber0.setBounds(210, 510, 190, 40);

        btnDecimalPt.setBackground(new java.awt.Color(255, 255, 0));
        btnDecimalPt.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnDecimalPt.setText(".");
        btnDecimalPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecimalPtActionPerformed(evt);
            }
        });
        getContentPane().add(btnDecimalPt);
        btnDecimalPt.setBounds(110, 510, 90, 40);

        btnOK.setBackground(new java.awt.Color(0, 204, 0));
        btnOK.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("OK");
        btnOK.setBorderPainted(false);
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK);
        btnOK.setBounds(410, 510, 190, 40);

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("CLR");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(10, 510, 90, 40);

        customerName.setFont(new java.awt.Font("Bahnschrift", 1, 60)); // NOI18N
        customerName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        customerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameActionPerformed(evt);
            }
        });
        getContentPane().add(customerName);
        customerName.setBounds(10, 100, 590, 90);

        lblPayment1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lblPayment1.setForeground(new java.awt.Color(255, 255, 102));
        lblPayment1.setText("Input the amount of cash received from the customer.");
        getContentPane().add(lblPayment1);
        lblPayment1.setBounds(10, 320, 460, 30);

        lblSuntea.setFont(new java.awt.Font("Bahnschrift", 0, 22)); // NOI18N
        lblSuntea.setForeground(new java.awt.Color(255, 255, 255));
        lblSuntea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSuntea.setText("Sta. Mesa, Manila");
        getContentPane().add(lblSuntea);
        lblSuntea.setBounds(190, 0, 230, 120);

        lblStaMesa.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        lblStaMesa.setForeground(new java.awt.Color(255, 255, 255));
        lblStaMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaMesa.setText("SUNTEA");
        getContentPane().add(lblStaMesa);
        lblStaMesa.setBounds(190, -30, 230, 120);

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setText("x");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblClose);
        lblClose.setBounds(570, 0, 29, 40);

        lblSunteaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/logosmall.png"))); // NOI18N
        lblSunteaLogo.setText("jLabel6");
        lblSunteaLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSunteaLogoMouseClicked(evt);
            }
        });
        getContentPane().add(lblSunteaLogo);
        lblSunteaLogo.setBounds(10, 0, 80, 90);

        lblYellowBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/yellow1.png"))); // NOI18N
        lblYellowBG.setText("CLICK THIS");
        getContentPane().add(lblYellowBG);
        lblYellowBG.setBounds(0, 0, 613, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashReceivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashReceivedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashReceivedActionPerformed

    private void btnNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber7ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber7.getText();
            cashReceived.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber7ActionPerformed

    private void lblSunteaLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSunteaLogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSunteaLogoMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.setVisible(false);  
      //  new PrmMOrdering().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber8ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber8.getText();
            cashReceived.setText(Enternumber);  
            lblAssign.setText(Enternumber);
            //txtScreen.getText(Enternumber);  // TODO add your handling code here:
    }//GEN-LAST:event_btnNumber8ActionPerformed

    private void btnNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber9ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber9.getText();
            cashReceived.setText(Enternumber);
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber9ActionPerformed

    private void btnNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber4ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber4.getText();
            cashReceived.setText(Enternumber); 
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber4ActionPerformed

    private void btnNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber5ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber5.getText();
            cashReceived.setText(Enternumber); 
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber5ActionPerformed

    private void btnNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber6ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber6.getText();
            cashReceived.setText(Enternumber);   
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber6ActionPerformed

    private void btnNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber1ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber1.getText();
            cashReceived.setText(Enternumber);    
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber1ActionPerformed

    private void btnNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber2ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber2.getText();
            cashReceived.setText(Enternumber); 
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber2ActionPerformed

    private void btnNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber3ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber3.getText();
            cashReceived.setText(Enternumber); 
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnNumber3ActionPerformed

    private void btnNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber0ActionPerformed
            String Enternumber = cashReceived.getText()+btnNumber0.getText();
            cashReceived.setText(Enternumber); 
            lblAssign.setText(Enternumber);
            
    }//GEN-LAST:event_btnNumber0ActionPerformed

    private void btnDecimalPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecimalPtActionPerformed
            String Enternumber = cashReceived.getText()+btnDecimalPt.getText();
            cashReceived.setText(Enternumber); 
            lblAssign.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_btnDecimalPtActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
            cashReceived.setText("");      
            lblAssign.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void customerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameActionPerformed

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
  
           
            
            //String cus = customerName.getText();
       
        
    }//GEN-LAST:event_btnOKMouseClicked

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        //String amt = jLabel1.getText();
        //jLabel1.setText(amt);
        //new POSNEW nf1 = new POSNEW();
        //POSNEW.lblPaymentAmount.setText(this.jLabel1.getText());
        
           
            
            if (  customerName.getText().trim().length() == 0 || cashReceived.getText().trim().length() == 0){
                new AllFieldsRequire().setVisible(true);
            }
            
            else {
           
                String Customer_name = customerName.getText();
        String received = cashReceived.getText();
        String date_ordered = POSNEW.lblDate.getText();
        String amount = POSNEW.lblPaymentAmount.getText();
       //String c1 = ah1.getText();
             float ttl = Float.parseFloat(POSNEW.lblTotal.getText());
             float dscnt = Float.parseFloat(POSNEW.lblAppliedDiscount.getText());
             float payment = ttl - dscnt;
            float cash = Float.parseFloat(cashReceived.getText()); 
          
            
            
            
        Connect();
        try {
            
            
           
            
            if (cash < payment){
                new Insufficient().setVisible(true);
                
            //this.setVisible(false);
            }
            
            else{
            pst = con.prepareStatement("update customer set Customer = ?");
            pst.setString(1, Customer_name);
           
            //pst.setString(3, amount);
            //pst.setString(2, date_ordered);
          
            pst.executeUpdate();
            
          
                 ReceiptFin recpt = new ReceiptFin();
            this.setExtendedState(ReceiptFin.MAXIMIZED_BOTH);
            recpt.setVisible(true);
            this.setVisible(false);
            
            
           
            } 
            
          
        } catch (SQLException ex) {
            Logger.getLogger(Calcu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
            
    
    
            
        //nf1.setVisible(true);
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecimalPt;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNumber0;
    private javax.swing.JButton btnNumber1;
    private javax.swing.JButton btnNumber2;
    private javax.swing.JButton btnNumber3;
    private javax.swing.JButton btnNumber4;
    private javax.swing.JButton btnNumber5;
    private javax.swing.JButton btnNumber6;
    private javax.swing.JButton btnNumber7;
    private javax.swing.JButton btnNumber8;
    private javax.swing.JButton btnNumber9;
    private javax.swing.JButton btnOK;
    public static javax.swing.JTextField cashReceived;
    public static javax.swing.JTextField customerName;
    private javax.swing.JLabel lblAssign;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblPayment1;
    private javax.swing.JLabel lblStaMesa;
    private javax.swing.JLabel lblSuntea;
    private javax.swing.JLabel lblSunteaLogo;
    private javax.swing.JLabel lblYellowBG;
    // End of variables declaration//GEN-END:variables
}
