package orderingsystem;


//import orderingsystem.Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author John
 */
public class Choose extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Choose() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChoose = new javax.swing.JPanel();
        lblManager = new javax.swing.JLabel();
        lblCashier = new javax.swing.JLabel();
        lblLoginAs = new javax.swing.JLabel();
        lblManagerIcon = new javax.swing.JLabel();
        lblCashierIcon = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblBgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlChoose.setLayout(null);

        lblManager.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblManager.setForeground(new java.awt.Color(255, 255, 255));
        lblManager.setText("MANAGER");
        pnlChoose.add(lblManager);
        lblManager.setBounds(390, 320, 120, 80);

        lblCashier.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblCashier.setForeground(new java.awt.Color(255, 255, 255));
        lblCashier.setText("CASHIER");
        pnlChoose.add(lblCashier);
        lblCashier.setBounds(190, 320, 110, 80);

        lblLoginAs.setFont(new java.awt.Font("Agency FB", 1, 45)); // NOI18N
        lblLoginAs.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginAs.setText("LOGIN AS");
        pnlChoose.add(lblLoginAs);
        lblLoginAs.setBounds(280, 130, 250, 60);

        lblManagerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/IconTwo.png"))); // NOI18N
        lblManagerIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManagerIconMouseClicked(evt);
            }
        });
        pnlChoose.add(lblManagerIcon);
        lblManagerIcon.setBounds(360, 160, 170, 210);

        lblCashierIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/IconOne.png"))); // NOI18N
        lblCashierIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCashierIconMouseClicked(evt);
            }
        });
        pnlChoose.add(lblCashierIcon);
        lblCashierIcon.setBounds(160, 160, 190, 210);

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/EKS.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        pnlChoose.add(lblExit);
        lblExit.setBounds(614, 0, 80, 80);

        lblBgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/BackgroundLogin.png"))); // NOI18N
        pnlChoose.add(lblBgLogin);
        lblBgLogin.setBounds(0, 0, 720, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChoose, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        dispose();  
        new FirstPart().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblCashierIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCashierIconMouseClicked
        dispose();
        Login log =new Login();
        log.setVisible(true);  
        Login.lblType.setText("CASHIER");
    }//GEN-LAST:event_lblCashierIconMouseClicked

    private void lblManagerIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagerIconMouseClicked
        dispose();
        Login logman = new Login();
        this.setExtendedState(logman.MAXIMIZED_BOTH);
        logman.setVisible(true);   
        Login.lblType.setText("MANAGER");
    }//GEN-LAST:event_lblManagerIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBgLogin;
    private javax.swing.JLabel lblCashier;
    public static javax.swing.JLabel lblCashierIcon;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLoginAs;
    private javax.swing.JLabel lblManager;
    public static javax.swing.JLabel lblManagerIcon;
    private javax.swing.JPanel pnlChoose;
    // End of variables declaration//GEN-END:variables
}
