package orderingsystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author rejean
 */
public class ConfirmLogout extends javax.swing.JFrame {

    /**
     * Creates new form Transactions
     */
    
    public ConfirmLogout() {
        initComponents();
        this.setSize(485, 266);
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlExitPrompt = new javax.swing.JPanel();
        lblEks = new javax.swing.JLabel();
        btnNoExit = new javax.swing.JButton();
        btnYesExit = new javax.swing.JButton();
        lblConLogBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlExitPrompt.setLayout(null);

        lblEks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/eksnew.png"))); // NOI18N
        lblEks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEksMouseClicked(evt);
            }
        });
        pnlExitPrompt.add(lblEks);
        lblEks.setBounds(420, 10, 70, 50);

        btnNoExit.setBackground(new java.awt.Color(255, 192, 0));
        btnNoExit.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnNoExit.setForeground(new java.awt.Color(255, 255, 255));
        btnNoExit.setText("No");
        btnNoExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNoExitMouseClicked(evt);
            }
        });
        btnNoExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoExitActionPerformed(evt);
            }
        });
        pnlExitPrompt.add(btnNoExit);
        btnNoExit.setBounds(290, 200, 110, 40);

        btnYesExit.setBackground(new java.awt.Color(255, 192, 0));
        btnYesExit.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnYesExit.setForeground(new java.awt.Color(255, 255, 255));
        btnYesExit.setText("Yes");
        btnYesExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnYesExitMouseClicked(evt);
            }
        });
        btnYesExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesExitActionPerformed(evt);
            }
        });
        pnlExitPrompt.add(btnYesExit);
        btnYesExit.setBounds(90, 200, 110, 40);

        lblConLogBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/logout.jpg"))); // NOI18N
        pnlExitPrompt.add(lblConLogBG);
        lblConLogBG.setBounds(0, -20, 490, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExitPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlExitPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEksMouseClicked
        dispose();  
        String unameNew = Login.uname; 
        POSNEW.cmboxAccount.insertItemAt(unameNew,0);
        POSNEW.cmboxAccount.setSelectedIndex(0); 
        new POSNEW().setVisible(true);
        //POSNEW.cmboxAccount.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_lblEksMouseClicked

    private void btnYesExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYesExitActionPerformed

    private void btnNoExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoExitActionPerformed

    private void btnYesExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnYesExitMouseClicked
        dispose();
        new FirstPart().setVisible(true);
        
      
    }//GEN-LAST:event_btnYesExitMouseClicked

    private void btnNoExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoExitMouseClicked
        dispose(); 
        String unameNew = Login.uname; 
        POSNEW.cmboxAccount.insertItemAt(unameNew,0);
        POSNEW.cmboxAccount.setSelectedIndex(0); 
        new POSNEW().setVisible(true);
        
        //POSNEW.cmboxAccount.setSelectedIndex(0);// TODO add your handling code here:
    }//GEN-LAST:event_btnNoExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmLogout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoExit;
    private javax.swing.JButton btnYesExit;
    private javax.swing.JLabel lblConLogBG;
    private javax.swing.JLabel lblEks;
    private javax.swing.JPanel pnlExitPrompt;
    // End of variables declaration//GEN-END:variables
}
