/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

/**
 *
 * @author rejean
 */
public class ExitSystem extends javax.swing.JFrame {

    /**
     * Creates new form Transactions
     */
    public ExitSystem() {
        initComponents();
        this.setSize(485, 276);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMessage = new javax.swing.JPanel();
        btnNoExit = new javax.swing.JButton();
        btnYesExit = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlMessage.setLayout(null);

        btnNoExit.setBackground(new java.awt.Color(255, 192, 0));
        btnNoExit.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnNoExit.setForeground(new java.awt.Color(255, 255, 255));
        btnNoExit.setText("No");
        btnNoExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoExitActionPerformed(evt);
            }
        });
        pnlMessage.add(btnNoExit);
        btnNoExit.setBounds(280, 200, 110, 40);

        btnYesExit.setBackground(new java.awt.Color(255, 192, 0));
        btnYesExit.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnYesExit.setForeground(new java.awt.Color(255, 255, 255));
        btnYesExit.setText("Yes");
        btnYesExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesExitActionPerformed(evt);
            }
        });
        pnlMessage.add(btnYesExit);
        btnYesExit.setBounds(90, 200, 110, 40);

        lblMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/exit.jpg"))); // NOI18N
        pnlMessage.add(lblMessage);
        lblMessage.setBounds(0, 0, 490, 276);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesExitActionPerformed
          System.exit(0);
    }//GEN-LAST:event_btnYesExitActionPerformed

    private void btnNoExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnNoExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNoExit;
    private javax.swing.JButton btnYesExit;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPanel pnlMessage;
    // End of variables declaration//GEN-END:variables
}
