package orderingsystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author John
 */
public class FirstPart extends javax.swing.JFrame {

    /**
     * Creates new form FirstPart
     */
    public FirstPart() {
        initComponents();
        setExtendedState(getExtendedState() | FirstPart.MAXIMIZED_BOTH);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFirst = new javax.swing.JPanel();
        lblBtnLogin = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblPremium = new javax.swing.JLabel();
        lblMaxi = new javax.swing.JLabel();
        lblFlexi = new javax.swing.JLabel();
        lblInfusions = new javax.swing.JLabel();
        lblSnacks = new javax.swing.JLabel();
        lblHeader = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblHeader2 = new javax.swing.JPanel();
        lblExitSystem = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlFirst.setLayout(null);

        lblBtnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Button.png"))); // NOI18N
        lblBtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnLoginMouseClicked(evt);
            }
        });
        pnlFirst.add(lblBtnLogin);
        lblBtnLogin.setBounds(510, 570, 380, 120);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Suntea Logo.png"))); // NOI18N
        pnlFirst.add(lblLogo);
        lblLogo.setBounds(0, 0, 240, 200);

        pnlMenu.setBackground(new java.awt.Color(198, 160, 7));
        pnlMenu.setForeground(new java.awt.Color(198, 160, 7));

        lblPremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Premium.jpg"))); // NOI18N

        lblMaxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Maxi Teas.jpg"))); // NOI18N

        lblFlexi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Flexi Teas.jpg"))); // NOI18N

        lblInfusions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Infusions.jpg"))); // NOI18N

        lblSnacks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Snacks.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(lblPremium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMaxi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFlexi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfusions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSnacks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFlexi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
            .addComponent(lblMaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblPremium, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInfusions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlFirst.add(pnlMenu);
        pnlMenu.setBounds(0, 150, 1370, 390);

        lblHeader.setBackground(new java.awt.Color(255, 204, 0));
        lblHeader.setForeground(new java.awt.Color(255, 204, 0));

        lblName.setFont(new java.awt.Font("Bahnschrift", 0, 86)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("SUNTEA ORDERING SYSTEM");

        javax.swing.GroupLayout lblHeaderLayout = new javax.swing.GroupLayout(lblHeader);
        lblHeader.setLayout(lblHeaderLayout);
        lblHeaderLayout.setHorizontalGroup(
            lblHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblHeaderLayout.createSequentialGroup()
                .addGap(0, 245, Short.MAX_VALUE)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblHeaderLayout.setVerticalGroup(
            lblHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblHeaderLayout.createSequentialGroup()
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );

        pnlFirst.add(lblHeader);
        lblHeader.setBounds(0, 40, 1370, 200);

        lblHeader2.setBackground(new java.awt.Color(255, 255, 0));
        lblHeader2.setForeground(new java.awt.Color(255, 255, 0));

        lblExitSystem.setFont(new java.awt.Font("Bahnschrift", 1, 33)); // NOI18N
        lblExitSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/FirstEKS.png"))); // NOI18N
        lblExitSystem.setText("X");
        lblExitSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitSystemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout lblHeader2Layout = new javax.swing.GroupLayout(lblHeader2);
        lblHeader2.setLayout(lblHeader2Layout);
        lblHeader2Layout.setHorizontalGroup(
            lblHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblHeader2Layout.createSequentialGroup()
                .addContainerGap(1314, Short.MAX_VALUE)
                .addComponent(lblExitSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        lblHeader2Layout.setVerticalGroup(
            lblHeader2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblHeader2Layout.createSequentialGroup()
                .addComponent(lblExitSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 83, Short.MAX_VALUE))
        );

        pnlFirst.add(lblHeader2);
        lblHeader2.setBounds(0, 0, 1370, 140);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Initial BG.JPG"))); // NOI18N
        pnlFirst.add(lblBackground);
        lblBackground.setBounds(0, 0, 1370, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnLoginMouseClicked
        this.dispose();
        new Choose().setVisible(true);
        
    }//GEN-LAST:event_lblBtnLoginMouseClicked

    private void lblExitSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitSystemMouseClicked
          new ExitSystem().setVisible(true);
    }//GEN-LAST:event_lblExitSystemMouseClicked
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPart().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBtnLogin;
    private javax.swing.JLabel lblExitSystem;
    private javax.swing.JLabel lblFlexi;
    private javax.swing.JPanel lblHeader;
    private javax.swing.JPanel lblHeader2;
    private javax.swing.JLabel lblInfusions;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMaxi;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPremium;
    private javax.swing.JLabel lblSnacks;
    private javax.swing.JPanel pnlFirst;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
