package orderingsystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author John
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public static int countIn = 0;
    public ForgotPassword() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        String type = Login.lblType.getText();
        lblTypes.setText(type);
        countIn=0;
        
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ordering", "root", "");
        }
        
        catch (ClassNotFoundException ex){
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pnlChangePass = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ExitPass = new javax.swing.JLabel();
        pnlFormBackground = new javax.swing.JPanel();
        lblChangePass = new javax.swing.JLabel();
        passfldEnterNewPass = new javax.swing.JPasswordField();
        lblEnterNewPass = new javax.swing.JLabel();
        passfldConfirmNewPass = new javax.swing.JPasswordField();
        lblTypes = new javax.swing.JLabel();
        lblConfirmNewPass = new javax.swing.JLabel();
        chckboxShowNewPass = new javax.swing.JCheckBox();
        btnUpdatePass = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlChangePass.setLayout(null);

        pnlBackground.setForeground(new java.awt.Color(240, 240, 240));
        pnlBackground.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 0));
        jPanel5.setToolTipText("");
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        ExitPass.setFont(new java.awt.Font("Bahnschrift", 1, 23)); // NOI18N
        ExitPass.setText("X");
        ExitPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitPassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitPass, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ExitPass))
        );

        pnlBackground.add(jPanel5);
        jPanel5.setBounds(426, 0, 50, 30);

        pnlChangePass.add(pnlBackground);
        pnlBackground.setBounds(-1, -1, 460, 30);

        pnlFormBackground.setBackground(new java.awt.Color(255, 204, 0));
        pnlFormBackground.setForeground(new java.awt.Color(240, 240, 240));

        lblChangePass.setFont(new java.awt.Font("Bahnschrift", 1, 45)); // NOI18N
        lblChangePass.setForeground(new java.awt.Color(255, 255, 255));
        lblChangePass.setText("Change Password");

        passfldEnterNewPass.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N

        lblEnterNewPass.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        lblEnterNewPass.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterNewPass.setText("ENTER NEW PASSWORD:");

        passfldConfirmNewPass.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        passfldConfirmNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfldConfirmNewPassActionPerformed(evt);
            }
        });

        lblTypes.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lblTypes.setForeground(new java.awt.Color(255, 255, 255));
        lblTypes.setLabelFor(lblTypes);

        lblConfirmNewPass.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        lblConfirmNewPass.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmNewPass.setText("CONFIRM NEW PASSWORD:");

        chckboxShowNewPass.setBackground(new java.awt.Color(255, 204, 0));
        chckboxShowNewPass.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        chckboxShowNewPass.setForeground(new java.awt.Color(255, 255, 255));
        chckboxShowNewPass.setText("Show New Password");
        chckboxShowNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckboxShowNewPassActionPerformed(evt);
            }
        });

        btnUpdatePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/UpdatePassword.jpg"))); // NOI18N
        btnUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormBackgroundLayout = new javax.swing.GroupLayout(pnlFormBackground);
        pnlFormBackground.setLayout(pnlFormBackgroundLayout);
        pnlFormBackgroundLayout.setHorizontalGroup(
            pnlFormBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormBackgroundLayout.createSequentialGroup()
                .addGroup(pnlFormBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormBackgroundLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlFormBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblConfirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnterNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passfldEnterNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                            .addComponent(chckboxShowNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passfldConfirmNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                            .addComponent(lblChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTypes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFormBackgroundLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnUpdatePass, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlFormBackgroundLayout.setVerticalGroup(
            pnlFormBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormBackgroundLayout.createSequentialGroup()
                .addGroup(pnlFormBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormBackgroundLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblTypes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblEnterNewPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passfldEnterNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(lblConfirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passfldConfirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chckboxShowNewPass))
                    .addGroup(pnlFormBackgroundLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdatePass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlChangePass.add(pnlFormBackground);
        pnlFormBackground.setBounds(0, 0, 460, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitPassMouseClicked
        
        new Choose().setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitPassMouseClicked

    private void passfldConfirmNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfldConfirmNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passfldConfirmNewPassActionPerformed

    private void chckboxShowNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckboxShowNewPassActionPerformed

        if (chckboxShowNewPass.isSelected())
        {
            passfldConfirmNewPass.setEchoChar((char)0);
        }
        else
        {
            passfldConfirmNewPass.setEchoChar('•');
        }

    }//GEN-LAST:event_chckboxShowNewPassActionPerformed

    private void btnUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePassActionPerformed

        String enterpass, confirmpass;
        enterpass = passfldEnterNewPass.getText();
        confirmpass = passfldConfirmNewPass.getText();
        
        
        
        String type = Login.lblType.getText();
        
        if (type == "CASHIER")
        {
            if (enterpass.equals("") || confirmpass.equals(""))
        {
           new AllFieldsRequire().setVisible(true);
           passfldEnterNewPass.setText("");
           passfldConfirmNewPass.setText("");  
           countIn++;
        }
        else
        {
            if (enterpass.equals(confirmpass))
            {
                
                dispose();
                new Password().setVisible(true);
                
                
            }
            else
            {
                
                new Unmatched().setVisible(true);
                passfldEnterNewPass.setText("");
                passfldConfirmNewPass.setText("");   
            }
        
        }    
             
        if(countIn == 0)
        {
          
       
        String newpassword = passfldConfirmNewPass.getText();
        
      
        Connect();
        try {
            
            pst = con.prepareStatement("update verify set PASSWORD = ?  where COMPANY_ROLE =?");
            pst.setString(1, newpassword);
            pst.setString(2, "Staff");
          
            pst.executeUpdate();
     
          
        } catch (SQLException ex) {
            Logger.getLogger(Calcu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
        
        if (type=="MANAGER")
        {
            if (enterpass.equals("") || confirmpass.equals(""))
        {
           new AllFieldsRequire().setVisible(true);
           passfldEnterNewPass.setText("");
           passfldConfirmNewPass.setText("");  
           countIn++;
        }
        else
        {
            if (enterpass.equals(confirmpass))
            {
                
                dispose();
                new Password().setVisible(true);
                
                
            }
            else
            {
                
                new Unmatched().setVisible(true);
                passfldEnterNewPass.setText("");
                passfldConfirmNewPass.setText("");   
            }
        
            
        }    
        
            if(countIn==0)
            {
            String newpassword = passfldConfirmNewPass.getText();
            
        Connect();
        try {
            
            pst = con.prepareStatement("update verify set PASSWORD = ?  where COMPANY_ROLE =?");
            pst.setString(1, newpassword);
            pst.setString(2, "Manager");
          
            pst.executeUpdate();
            
    
            
           
         
            
          
        } catch (SQLException ex) {
            Logger.getLogger(Calcu.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
        
    }//GEN-LAST:event_btnUpdatePassActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitPass;
    private javax.swing.JButton btnUpdatePass;
    private javax.swing.JCheckBox chckboxShowNewPass;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblChangePass;
    private javax.swing.JLabel lblConfirmNewPass;
    private javax.swing.JLabel lblEnterNewPass;
    public static javax.swing.JLabel lblTypes;
    private javax.swing.JPasswordField passfldConfirmNewPass;
    private javax.swing.JPasswordField passfldEnterNewPass;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlChangePass;
    private javax.swing.JPanel pnlFormBackground;
    // End of variables declaration//GEN-END:variables
}
