/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Joecharmie
 */
public class frmInvAdd1 extends javax.swing.JFrame {

    /**
     * Creates new form frmInvEdit
     */
    public frmInvAdd1() {
        initComponents();
        lblUnit.setVisible(false);
        cmbUnits.setVisible(false);
        
              
    }
    frmMessage frmMessage = new frmMessage();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddItem = new javax.swing.JPanel();
        lblAddTitle = new javax.swing.JLabel();
        lblActiveStatus = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAddItem = new javax.swing.JButton();
        lblStockLevel = new javax.swing.JLabel();
        txtStockLevel = new javax.swing.JTextField();
        cmbUnits = new javax.swing.JComboBox<>();
        lblUnit = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblAddTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD");
        setIconImages(null);
        setLocation(new java.awt.Point(450, 100));
        setUndecorated(true);
        setSize(new java.awt.Dimension(450, 540));

        pnlAddItem.setBackground(new java.awt.Color(254, 190, 6));

        lblAddTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblAddTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAddTitle.setText("Add New Item");

        lblActiveStatus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblActiveStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblActiveStatus.setText("ACTIVE STATUS:");

        lblItemCode.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblItemCode.setForeground(new java.awt.Color(255, 255, 255));
        lblItemCode.setText("ITEM CODE:");

        lblItemName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(255, 255, 255));
        lblItemName.setText("ITEM NAME:");

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("CATEGORY:");

        txtItemCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtItemCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtItemCodeMouseClicked(evt);
            }
        });

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtItemName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtItemNameMouseClicked(evt);
            }
        });

        cmbCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drinks", "Snacks" }));

        cmbStatus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Stock", "Low on Stock", "Out of Stock" }));

        btnAddItem.setBackground(new java.awt.Color(254, 255, 0));
        btnAddItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddItem.setText("ADD ITEM");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        lblStockLevel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblStockLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblStockLevel.setText("STOCK LEVEL:");

        txtStockLevel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtStockLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStockLevelMouseClicked(evt);
            }
        });
        txtStockLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockLevelKeyTyped(evt);
            }
        });

        cmbUnits.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbUnits.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PIECES", "PACK", "BOX" }));

        lblUnit.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblUnit.setForeground(new java.awt.Color(255, 255, 255));
        lblUnit.setText("UNIT:");

        lblQty.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblQty.setForeground(new java.awt.Color(255, 255, 255));
        lblQty.setText("QUANTITY:");

        txtQty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtyMouseClicked(evt);
            }
        });
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });

        lblAddTitle1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAddTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddTitle1.setText("X");
        lblAddTitle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddTitle1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAddItemLayout = new javax.swing.GroupLayout(pnlAddItem);
        pnlAddItem.setLayout(pnlAddItemLayout);
        pnlAddItemLayout.setHorizontalGroup(
            pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddItemLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAddItemLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddItemLayout.createSequentialGroup()
                        .addComponent(lblCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblActiveStatus)
                        .addGap(44, 44, 44))
                    .addGroup(pnlAddItemLayout.createSequentialGroup()
                        .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblQty)
                            .addComponent(txtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(lblItemCode)
                            .addComponent(lblItemName)
                            .addComponent(txtItemName, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(txtItemCode))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAddItemLayout.createSequentialGroup()
                        .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlAddItemLayout.createSequentialGroup()
                                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlAddItemLayout.createSequentialGroup()
                                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStockLevel)
                                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnit))))
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddItemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddItemLayout.createSequentialGroup()
                        .addComponent(lblAddTitle)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddItemLayout.createSequentialGroup()
                        .addComponent(lblAddTitle1)
                        .addContainerGap())))
        );
        pnlAddItemLayout.setVerticalGroup(
            pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItemName)
                .addGap(7, 7, 7)
                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQty)
                .addGap(7, 7, 7)
                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActiveStatus)
                    .addComponent(lblCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockLevel)
                    .addComponent(lblUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUnits, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        try{
            if("".equalsIgnoreCase(txtItemCode.getText()) || "".equalsIgnoreCase(txtItemName.getText()) || "".equalsIgnoreCase(txtQty.getText()) || "".equalsIgnoreCase(txtStockLevel.getText()))                
            {
                while("".equalsIgnoreCase(txtItemCode.getText()))
                {
                    txtItemCode.setForeground(Color.red);
                    txtItemCode.setText("Field Required");                    
                }
                while("".equalsIgnoreCase(txtItemName.getText()))
                {
                    txtItemName.setForeground(Color.red);
                    txtItemName.setText("Field Required");  
                }
                while("".equalsIgnoreCase(txtQty.getText()))
                {
                    txtQty.setForeground(Color.red);
                    txtQty.setText("Field Required");  
                }
                while("".equalsIgnoreCase(txtStockLevel.getText()))
                {
                    txtStockLevel.setForeground(Color.red);
                    txtStockLevel.setText("Field Required");  
                }                
            }
            else{
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ordering","root","")) {
                PreparedStatement ps = con.prepareStatement("insert into supplies(SUPPLIES_ID,ITEM_CODE,ITEM_NAME,ITEM_QTY,ITEM_STATUS,ITEM_CATEGORY,STOCK_LEVEL,DATE_ADDED,DATE_UPDATED) values (NULL,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
                ps.setString(1,txtItemCode.getText());
                ps.setString(2,txtItemName.getText());
                ps.setString(3,txtQty.getText());
                ps.setString(4,cmbStatus.getSelectedItem().toString());
                ps.setString(5,cmbCategory.getSelectedItem().toString());
                ps.setString(6,txtStockLevel.getText());
                ps.executeUpdate();
                con.close();
                this.dispose();
                frmMessage.setVisible(true);
                frmMessage.lblMessage.setText(txtItemCode.getText()+" has been Added to Supplies");
                }
            }       
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }           
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void lblAddTitle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddTitle1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblAddTitle1MouseClicked

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtQtyKeyTyped

    private void txtStockLevelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockLevelKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtStockLevelKeyTyped

    private void txtItemCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtItemCodeMouseClicked
        // TODO add your handling code here:
        txtItemCode.setForeground(Color.black);
        txtItemCode.setText("");
    }//GEN-LAST:event_txtItemCodeMouseClicked

    private void txtItemNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtItemNameMouseClicked
        // TODO add your handling code here:
        txtItemName.setForeground(Color.black);
        txtItemName.setText("");
    }//GEN-LAST:event_txtItemNameMouseClicked

    private void txtQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtyMouseClicked
        // TODO add your handling code here:
        txtQty.setForeground(Color.black);
        txtQty.setText("");
    }//GEN-LAST:event_txtQtyMouseClicked

    private void txtStockLevelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStockLevelMouseClicked
        // TODO add your handling code here:
        txtStockLevel.setForeground(Color.black);
        txtStockLevel.setText("");
    }//GEN-LAST:event_txtStockLevelMouseClicked

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInvAdd1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInvAdd1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInvAdd1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInvAdd1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmInvAdd1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbUnits;
    private javax.swing.JLabel lblActiveStatus;
    private javax.swing.JLabel lblAddTitle;
    private javax.swing.JLabel lblAddTitle1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblStockLevel;
    private javax.swing.JLabel lblUnit;
    private javax.swing.JPanel pnlAddItem;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}
