/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Joecharmie
 */
public class frmInvEdit1 extends javax.swing.JFrame {

    /**
     * Creates new form frmInvEdit
     */
    public frmInvEdit1() {
        initComponents();
        txtItemName.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    frmMessage frmMessage = new frmMessage();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEdit = new javax.swing.JPanel();
        lblItemNameHead = new javax.swing.JLabel();
        lblCLose = new javax.swing.JLabel();
        lblActiveStatus = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblItemcode = new javax.swing.JLabel();
        lblItemname = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        btnConfirmEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDIT");
        setLocation(new java.awt.Point(450, 100));
        setUndecorated(true);
        setSize(new java.awt.Dimension(450, 540));

        pnlEdit.setBackground(new java.awt.Color(254, 190, 6));
        pnlEdit.setPreferredSize(new java.awt.Dimension(450, 540));

        lblItemNameHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblItemNameHead.setForeground(new java.awt.Color(255, 255, 255));
        lblItemNameHead.setText("Item Name");

        lblCLose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCLose.setForeground(new java.awt.Color(255, 255, 255));
        lblCLose.setText("X");
        lblCLose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCLoseMouseClicked(evt);
            }
        });

        lblActiveStatus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblActiveStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblActiveStatus.setText("ITEM STATUS:");

        lblItemCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblItemCode.setForeground(new java.awt.Color(255, 255, 255));
        lblItemCode.setText("SAMPLE0000");

        lblItemcode.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblItemcode.setForeground(new java.awt.Color(255, 255, 255));
        lblItemcode.setText("ITEM CODE:");

        lblItemname.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblItemname.setForeground(new java.awt.Color(255, 255, 255));
        lblItemname.setText("ITEM NAME:");

        lblCategory.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("CATEGORY:");

        txtItemCode.setEditable(false);
        txtItemCode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtItemName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtItemNameMouseClicked(evt);
            }
        });

        cmbCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drinks", "Snacks" }));

        cmbStatus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Stock", "Low on Stock", "Out of Stock" }));
        cmbStatus.setEnabled(false);
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        btnConfirmEdit.setBackground(new java.awt.Color(254, 255, 0));
        btnConfirmEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConfirmEdit.setText("CONFIRM EDIT");
        btnConfirmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditLayout = new javax.swing.GroupLayout(pnlEdit);
        pnlEdit.setLayout(pnlEditLayout);
        pnlEditLayout.setHorizontalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCLose))
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEditLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(lblItemcode))
                                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(lblActiveStatus))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(lblCategory))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(lblItemname))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblItemNameHead)
                                    .addComponent(lblItemCode)))
                            .addGroup(pnlEditLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btnConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEditLayout.setVerticalGroup(
            pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditLayout.createSequentialGroup()
                .addGroup(pnlEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCLose))
                    .addGroup(pnlEditLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblItemNameHead)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(lblItemcode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItemname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCategory)
                .addGap(18, 18, 18)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblActiveStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEditActionPerformed
        
        try {
            
            if("".equalsIgnoreCase(txtItemName.getText()))
            {
                while("".equalsIgnoreCase(txtItemName.getText()))
                {
                    txtItemName.setForeground(Color.red);
                    txtItemName.setText("Field Required");                    
                } 
            }
            else
            {
            try (  //Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ordering","root","")) {
                String prev = lblItemCode.getText();
                PreparedStatement pst = con.prepareStatement("SELECT SUPPLIES_ID from supplies where ITEM_CODE = '"+prev+"'");
                ResultSet rs = pst.executeQuery();
                
                while(rs.next())
                {
                    int intRow = rs.getInt("SUPPLIES_ID");
                    String update = "UPDATE supplies set ITEM_CODE ='"+txtItemCode.getText()+"',ITEM_NAME ='"+txtItemName.getText()+"', ITEM_STATUS ='"+cmbStatus.getSelectedItem()+"', ITEM_CATEGORY = '"+cmbCategory.getSelectedItem()+"' where SUPPLIES_ID ="+intRow;
                    PreparedStatement ps = con.prepareStatement(update);
                    ps.executeUpdate();
                }
                con.close();
                this.dispose();
                frmMessage.setVisible(true);
                frmMessage.lblMessage.setText("Your Edit Transaction is Successful");
            }
            }
              
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_btnConfirmEditActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void lblCLoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCLoseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_lblCLoseMouseClicked

    private void txtItemNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtItemNameMouseClicked
        txtItemName.setForeground(Color.black);
        txtItemName.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInvEdit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInvEdit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInvEdit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInvEdit1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmInvEdit1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmEdit;
    public javax.swing.JComboBox<String> cmbCategory;
    public javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel lblActiveStatus;
    public javax.swing.JLabel lblCLose;
    private javax.swing.JLabel lblCategory;
    public javax.swing.JLabel lblItemCode;
    public javax.swing.JLabel lblItemNameHead;
    private javax.swing.JLabel lblItemcode;
    private javax.swing.JLabel lblItemname;
    public javax.swing.JPanel pnlEdit;
    public javax.swing.JTextField txtItemCode;
    public javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables
}
