/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Joecharmie
 */
public class frmInvDeduct1 extends javax.swing.JFrame {

    /**
     * Creates new form frmInvDeduct1
     */
    public frmInvDeduct1() {
        initComponents();
        txtLastQty.setEnabled(false);
        txtNewQty.setEnabled(false);
        txtDeductQty.requestFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    frmMessage frmMessage = new frmMessage();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblItemName = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        lblDeductDty = new javax.swing.JLabel();
        lblLastQty = new javax.swing.JLabel();
        lblRemarks = new javax.swing.JLabel();
        lblNewQty = new javax.swing.JLabel();
        txtLastQty = new javax.swing.JTextField();
        txtDeductQty = new javax.swing.JTextField();
        btnGo = new javax.swing.JButton();
        txtRemarks = new javax.swing.JTextField();
        txtNewQty = new javax.swing.JTextField();
        lneBlack = new javax.swing.JPanel();
        btnDeduct = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DEDUCT");
        setBackground(new java.awt.Color(254, 192, 6));
        setLocation(new java.awt.Point(450, 100));
        setUndecorated(true);
        setSize(new java.awt.Dimension(450, 540));

        jPanel1.setBackground(new java.awt.Color(254, 192, 6));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 540));

        lblItemName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(255, 255, 255));
        lblItemName.setText("Item Name");

        lblItemCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblItemCode.setForeground(new java.awt.Color(255, 255, 255));
        lblItemCode.setText("SAMPLE0000");

        lblDeductDty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDeductDty.setForeground(new java.awt.Color(255, 255, 255));
        lblDeductDty.setText("Deduct Quantity");

        lblLastQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLastQty.setForeground(new java.awt.Color(255, 255, 255));
        lblLastQty.setText("Last Quantity");

        lblRemarks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRemarks.setForeground(new java.awt.Color(255, 255, 255));
        lblRemarks.setText("Remarks");

        lblNewQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNewQty.setForeground(new java.awt.Color(255, 255, 255));
        lblNewQty.setText("New Quantity");

        txtLastQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtLastQty.setForeground(new java.awt.Color(255, 255, 255));
        txtLastQty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDeductQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnGo.setBackground(new java.awt.Color(254, 255, 0));
        btnGo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGo.setText("Deduct");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        txtRemarks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtNewQty.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtNewQty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lneBlack.setBackground(new java.awt.Color(0, 0, 0));
        lneBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout lneBlackLayout = new javax.swing.GroupLayout(lneBlack);
        lneBlack.setLayout(lneBlackLayout);
        lneBlackLayout.setHorizontalGroup(
            lneBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lneBlackLayout.setVerticalGroup(
            lneBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        btnDeduct.setBackground(new java.awt.Color(254, 255, 0));
        btnDeduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeduct.setText("Confirm Deduction");
        btnDeduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeductActionPerformed(evt);
            }
        });

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lneBlack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnDeduct, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(txtNewQty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemCode)
                            .addComponent(lblItemName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLastQty)
                                    .addComponent(txtLastQty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRemarks))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtDeductQty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDeductDty))))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNewQty)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblClose)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lblClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblItemCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastQty)
                    .addComponent(lblDeductDty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeductQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblRemarks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lneBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNewQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNewQty, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeduct, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnDeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeductActionPerformed
        // TODO add your handling code here:
       try {
            try (  //Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ordering","root","")) {
                String prev = lblItemCode.getText();
                PreparedStatement pst = con.prepareStatement("SELECT SUPPLIES_ID from supplies where ITEM_CODE = '"+prev+"'");
                ResultSet rs = pst.executeQuery();
                
                while(rs.next())
                {
                    int intRow = rs.getInt("SUPPLIES_ID");
                    String update = "UPDATE supplies set ITEM_QTY ='"+txtNewQty.getText()+"' where SUPPLIES_ID ="+intRow;
                    PreparedStatement ps = con.prepareStatement(update);
                    ps.executeUpdate();
                }
             con.close();
            }
        }
       catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        this.dispose();
        frmMessage.setVisible(true);
        frmMessage.lblMessage.setText(lblItemCode.getText()+"'s quantity has been updated");
    }//GEN-LAST:event_btnDeductActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        int intDeduct = Integer.parseInt(txtDeductQty.getText());
        int intPrev = Integer.parseInt(txtLastQty.getText());
        String strnew = String.valueOf(intPrev - intDeduct);
        txtNewQty.setText(strnew);
    }//GEN-LAST:event_btnGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInvDeduct1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInvDeduct1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInvDeduct1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInvDeduct1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmInvDeduct1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeduct;
    private javax.swing.JButton btnGo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblDeductDty;
    public javax.swing.JLabel lblItemCode;
    public javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblLastQty;
    private javax.swing.JLabel lblNewQty;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JPanel lneBlack;
    public javax.swing.JTextField txtDeductQty;
    public javax.swing.JTextField txtLastQty;
    public javax.swing.JTextField txtNewQty;
    private javax.swing.JTextField txtRemarks;
    // End of variables declaration//GEN-END:variables
}
