/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

/**
 *
 * @author Joecharmie
 */
public class frmInvLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmInvLogin
     */
    public frmInvLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        imgHomeLogo = new javax.swing.JLabel();
        shpYellow1 = new javax.swing.JPanel();
        shpYellow2 = new javax.swing.JPanel();
        lblHomeTitle = new javax.swing.JLabel();
        btnHomeLogin = new javax.swing.JButton();
        shpYellow3 = new javax.swing.JPanel();
        imgCover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suntea Inventory System");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(1366, 768));

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Path");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField1.setText("Milktea > Login");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 30);
        jPanel1.add(imgHomeLogo);
        imgHomeLogo.setBounds(10, 90, 0, 250);

        shpYellow1.setBackground(new java.awt.Color(254, 255, 6));
        shpYellow1.setMinimumSize(new java.awt.Dimension(1366, 50));
        shpYellow1.setPreferredSize(new java.awt.Dimension(1366, 50));

        javax.swing.GroupLayout shpYellow1Layout = new javax.swing.GroupLayout(shpYellow1);
        shpYellow1.setLayout(shpYellow1Layout);
        shpYellow1Layout.setHorizontalGroup(
            shpYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        shpYellow1Layout.setVerticalGroup(
            shpYellow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(shpYellow1);
        shpYellow1.setBounds(0, 30, 1366, 30);

        shpYellow2.setBackground(new java.awt.Color(254, 192, 0));
        shpYellow2.setMinimumSize(new java.awt.Dimension(1366, 30));
        shpYellow2.setPreferredSize(new java.awt.Dimension(1366, 30));
        shpYellow2.setLayout(null);
        shpYellow2.add(lblHomeTitle);
        lblHomeTitle.setBounds(220, 90, 0, 120);

        btnHomeLogin.setBackground(new java.awt.Color(254, 192, 0));
        shpYellow2.add(btnHomeLogin);
        btnHomeLogin.setBounds(550, 240, 310, 75);

        jPanel1.add(shpYellow2);
        shpYellow2.setBounds(0, 190, 1366, 350);

        shpYellow3.setBackground(new java.awt.Color(254, 255, 6));
        shpYellow3.setMinimumSize(new java.awt.Dimension(1366, 30));

        javax.swing.GroupLayout shpYellow3Layout = new javax.swing.GroupLayout(shpYellow3);
        shpYellow3.setLayout(shpYellow3Layout);
        shpYellow3Layout.setHorizontalGroup(
            shpYellow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        shpYellow3Layout.setVerticalGroup(
            shpYellow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(shpYellow3);
        shpYellow3.setBounds(0, 720, 1366, 50);
        jPanel1.add(imgCover);
        imgCover.setBounds(0, 0, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInvLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInvLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInvLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInvLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInvLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHomeLogin;
    private javax.swing.JLabel imgCover;
    private javax.swing.JLabel imgHomeLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblHomeTitle;
    private javax.swing.JPanel shpYellow1;
    private javax.swing.JPanel shpYellow2;
    private javax.swing.JPanel shpYellow3;
    // End of variables declaration//GEN-END:variables
}
