/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Joecharmie
 */
public class frmView extends javax.swing.JFrame {

    /**
     * Creates new form frmInvEdit
     */
    public frmView() {
        initComponents();
       /* try {
            try (  //Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/ordering","root","")) {
                String prev = lblItemCode.getText();
                //PreparedStatement pst = con.prepareStatement("SELECT a.DATE, a.ACTIVITY, a.QUANTITY,  from activity a, supplies s where ITEM_CODE = '"+prev+"'");
                ResultSet rs = pst.executeQuery();
                
                while(rs.next())
                {
                    int intRow = rs.getInt("SUPPLIES_ID");
                    //String update = "UPDATE supplies set ITEM_CODE ='"+txtItemCode.getText()+"',ITEM_NAME ='"+txtItemName.getText()+"', ITEM_STATUS ='"+cmbStatus.getSelectedItem()+"', ITEM_CATEGORY = '"+cmbCategory.getSelectedItem()+"' where SUPPLIES_ID ="+intRow;
                    //PreparedStatement ps = con.prepareStatement(update);
                    //ps.executeUpdate();
                }
                con.close();
            }
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        this.dispose();  */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    frmMessage frmMessage = new frmMessage();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlView = new javax.swing.JPanel();
        lblItemName = new javax.swing.JLabel();
        lblCLose = new javax.swing.JLabel();
        lblItemCode = new javax.swing.JLabel();
        srclView = new javax.swing.JScrollPane();
        tblActivity = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EDIT");
        setLocation(new java.awt.Point(450, 100));
        setUndecorated(true);
        setSize(new java.awt.Dimension(450, 540));

        pnlView.setBackground(new java.awt.Color(254, 190, 6));
        pnlView.setPreferredSize(new java.awt.Dimension(450, 540));

        lblItemName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(255, 255, 255));
        lblItemName.setText("Item Name");

        lblCLose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCLose.setForeground(new java.awt.Color(255, 255, 255));
        lblCLose.setText("X");
        lblCLose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCLoseMouseClicked(evt);
            }
        });

        lblItemCode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblItemCode.setForeground(new java.awt.Color(255, 255, 255));
        lblItemCode.setText("SAMPLE0000");

        tblActivity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Activity", "Qty", "Total Qty", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        srclView.setViewportView(tblActivity);

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCLose))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(srclView, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemName)
                            .addComponent(lblItemCode))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewLayout.createSequentialGroup()
                .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCLose))
                    .addGroup(pnlViewLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblItemName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblItemCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(srclView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlView, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlView, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCLoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCLoseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_lblCLoseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblCLose;
    public javax.swing.JLabel lblItemCode;
    public javax.swing.JLabel lblItemName;
    public javax.swing.JPanel pnlView;
    private javax.swing.JScrollPane srclView;
    private javax.swing.JTable tblActivity;
    // End of variables declaration//GEN-END:variables
}
