package orderingsystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author John
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public static String uname="";
    public static int ctrCombo = 0;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        ctrCombo=0;
        
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ordering", "root", "");
        }
        
        catch (ClassNotFoundException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        passfldPassword = new javax.swing.JPasswordField();
        chckboxShowPassword = new javax.swing.JCheckBox();
        pnlClose = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        lblForgorPassword = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlLogin.setBackground(new java.awt.Color(255, 204, 0));
        pnlLogin.setLayout(null);

        lblLogin.setFont(new java.awt.Font("Bahnschrift", 1, 80)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Log-in");
        pnlLogin.add(lblLogin);
        lblLogin.setBounds(130, 30, 400, 110);

        txtId.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        pnlLogin.add(txtId);
        txtId.setBounds(40, 200, 460, 40);

        lblId.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID NUMBER:");
        pnlLogin.add(lblId);
        lblId.setBounds(40, 150, 240, 60);

        txtName.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlLogin.add(txtName);
        txtName.setBounds(40, 300, 460, 40);

        lblName.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("NAME:");
        pnlLogin.add(lblName);
        lblName.setBounds(40, 240, 290, 80);

        lblPassword.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("PASSWORD:");
        pnlLogin.add(lblPassword);
        lblPassword.setBounds(40, 350, 210, 60);

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/LoginButton.jpg"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLogin.add(btnLogin);
        btnLogin.setBounds(180, 480, 180, 60);

        passfldPassword.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        passfldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passfldPasswordActionPerformed(evt);
            }
        });
        pnlLogin.add(passfldPassword);
        passfldPassword.setBounds(40, 400, 460, 40);

        chckboxShowPassword.setBackground(new java.awt.Color(255, 204, 0));
        chckboxShowPassword.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        chckboxShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        chckboxShowPassword.setText("Show Password");
        chckboxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckboxShowPasswordActionPerformed(evt);
            }
        });
        pnlLogin.add(chckboxShowPassword);
        chckboxShowPassword.setBounds(40, 440, 170, 40);

        pnlClose.setBackground(new java.awt.Color(255, 240, 0));

        lblClose.setFont(new java.awt.Font("Bahnschrift", 1, 25)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pnlClose.add(lblClose);

        pnlLogin.add(pnlClose);
        pnlClose.setBounds(490, 0, 50, 40);
        pnlLogin.add(pnlBackground);
        pnlBackground.setBounds(0, 0, 540, 40);

        lblForgorPassword.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        lblForgorPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblForgorPassword.setText("Forgot Password?");
        lblForgorPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgorPasswordMouseClicked(evt);
            }
        });
        pnlLogin.add(lblForgorPassword);
        lblForgorPassword.setBounds(360, 440, 160, 40);

        lblType.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 255, 255));
        pnlLogin.add(lblType);
        lblType.setBounds(230, 120, 150, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String type = lblType.getText();
        
        
        if(type == "CASHIER")
        {
        String id = txtId.getText();
        String user = txtName.getText();
        String password = passfldPassword.getText();
        Connect();
        
        if ( (id.equals("")) || (user.equals("")) || (password.equals("")) ){
                new AllFieldsRequire().setVisible(true);
                txtId.setText("");
                txtName.setText("");       
                passfldPassword.setText("");
                
		
        }
        else
        {
        try { 
            pst = con.prepareStatement("Select * from verify where PASSWORD = ? and COMPANY_ROLE = ?");
            pst.setString(1,password);
            pst.setString(2,"Staff");
            rs = pst.executeQuery();
            ResultSetMetaData Rsm1 = rs.getMetaData();
            

        

            
            if (rs.next()) {
                                String pass =rs.getString("PASSWORD");
                	

                		if ( (id.equals("SUNTEAPH01")) && (user.equals(user)) && (password.equals(pass)))
                 		{
					dispose();
                                        POSNEW pos = new POSNEW(); 
                                        pos.setVisible(true);
                                        
                                        //POSNEW.cmboxAccount.setSelectedItem(user);
                                        //POSNEW.cmboxAccount.removeItemAt(0);
                                        POSNEW.cmboxAccount.insertItemAt(user,0);
                                        //POSNEW.cmboxAccount.setSelectedItem(user);
                                        POSNEW.cmboxAccount.setSelectedIndex(0);
                                         uname = user;
                                        
      
                 		}
                                else{
                 			new InvalidAccount().setVisible(true);
                                        txtId.setText("");
                                        txtName.setText("");       
                                        passfldPassword.setText("");
                 		}
                		
               
            }
            else{
                 			new InvalidAccount().setVisible(true);
                                        txtId.setText("");
                                        txtName.setText("");       
                                        passfldPassword.setText("");
                 		}
	
        }catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        }
        
        if(type == "MANAGER")
        {
            String id = txtId.getText();
            String user = txtName.getText();
            String password = passfldPassword.getText();
            Connect();

	if ( (id.equals("")) || (user.equals("")) || (password.equals("")) ){
                new AllFieldsRequire().setVisible(true);
                txtId.setText("");
                txtName.setText("");       
                passfldPassword.setText("");
            }

        	 
        else
        {
        try { 
            pst = con.prepareStatement("Select * from verify where PASSWORD = ? and COMPANY_ROLE = ?");
            pst.setString(1,password);
            pst.setString(2,"Manager");
            rs = pst.executeQuery();
            ResultSetMetaData Rsm1 = rs.getMetaData();
            

        

            
            if (rs.next()) {
                                String pass =rs.getString("PASSWORD");
                	

                		if ( (id.equals("SUNTEAPHMAN02")) && (user.equals(user)) && (password.equals(pass)))
                 		{
					dispose();
                                        
                                        POSNEW pos = new POSNEW(); 
                                        pos.setVisible(true);
                                        
                                                
                                        POSNEW.cmboxAccount.insertItemAt(user,0);
                                        POSNEW.cmboxAccount.setSelectedIndex(0);
                                        frmInvMain.cmbInvAccount.insertItemAt(user,0);
                                        frmInvMain.cmbInvAccount.setSelectedIndex(0);
                                        uname = user;
                                        ctrCombo=0;
                 		}
                                else{
                 			new InvalidAccount().setVisible(true);
                                        txtId.setText("");
                                        txtName.setText("");       
                                        passfldPassword.setText("");
                 		}
                		
               
            }
            else{
                 			new InvalidAccount().setVisible(true);
                                        txtId.setText("");
                                        txtName.setText("");       
                                        passfldPassword.setText("");
                 		}
	
        }catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        }    
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void passfldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passfldPasswordActionPerformed
        
    }//GEN-LAST:event_passfldPasswordActionPerformed

    private void chckboxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckboxShowPasswordActionPerformed

            if (chckboxShowPassword.isSelected())
            {
                passfldPassword.setEchoChar((char)0);
            }
            else
            {
                passfldPassword.setEchoChar('•');
            }
       
    }//GEN-LAST:event_chckboxShowPasswordActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
            dispose();
            new Choose().setVisible(true);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblForgorPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgorPasswordMouseClicked
          
        dispose();
        new Verify().setVisible(true); 
    }//GEN-LAST:event_lblForgorPasswordMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        
    }//GEN-LAST:event_btnLoginMouseClicked

    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chckboxShowPassword;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblForgorPassword;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    public static javax.swing.JLabel lblType;
    private javax.swing.JPasswordField passfldPassword;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlClose;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
