/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderingsystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author John
 */
public class MaxCOrdering extends javax.swing.JFrame {

    /**
     * Creates new form FlexiTeasOrder
     */
    int intQuantityBoba = 0;
    int intQuantityNata = 0;
    int intQuantityPop = 0;
    int intQuantityFruit = 0;
    int intQuantityFoam = 0;
    int intQuantity = 1;
    float fltPrice;
    float fltAmount;
    public MaxCOrdering() {
        initComponents();
        this.setSize(971, 669);
        this.setLocationRelativeTo(null);
        txtQuantityBoba.setText("0");
        txtQuantityNata.setText("0");
        txtQuantityPop.setText("0");
        txtQuantityFruit.setText("0");
        txtQuantityFoam.setText("0");
        txtQuantity.setText("1");  
        txtAmount.setText("0.0");
        txtQuantityBoba.setEditable(false);
        txtQuantityNata.setEditable(false);
        txtQuantityPop.setEditable(false);
        txtQuantityFruit.setEditable(false);
        txtQuantityFoam.setEditable(false);
        txtQuantity.setEditable(false);
        txtAmount.setEditable(false);
        outofstock_500ml.setVisible(false);
        outofstock_700ml.setVisible(false);
        Connect();
        cups500();
        cups700();
        plus_500();
        plus_700();

    }
    Connection con;
    PreparedStatement pst;
    PreparedStatement pst2;
    PreparedStatement pst3;
    PreparedStatement pst4;
    ResultSet rs;
    ResultSet rs2;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/ordering", "root", "");
        }
        
        catch (ClassNotFoundException ex){
            Logger.getLogger(MaxCOrdering.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MaxCOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblPath = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        lblProductPic = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblPrizeSize = new javax.swing.JLabel();
        txtSpecialInstruct = new javax.swing.JTextField();
        lblAddRider = new javax.swing.JLabel();
        btnMinusBoba = new javax.swing.JButton();
        txtQuantityBoba = new javax.swing.JTextField();
        btnPlusBoba = new javax.swing.JButton();
        btnMinusNata = new javax.swing.JButton();
        outofstock_500ml = new javax.swing.JLabel();
        outofstock_700ml = new javax.swing.JLabel();
        txtQuantityNata = new javax.swing.JTextField();
        btnPlusNata = new javax.swing.JButton();
        btnMinusPop = new javax.swing.JButton();
        txtQuantityPop = new javax.swing.JTextField();
        btnPlusPop = new javax.swing.JButton();
        btnMinusFruit = new javax.swing.JButton();
        txtQuantityFruit = new javax.swing.JTextField();
        btnPlusFruit = new javax.swing.JButton();
        btnMinusFoam = new javax.swing.JButton();
        txtQuantityFoam = new javax.swing.JTextField();
        btnPlusFoam = new javax.swing.JButton();
        togbtn500 = new javax.swing.JToggleButton();
        lblSpecialInstruct1 = new javax.swing.JLabel();
        togbtn700 = new javax.swing.JToggleButton();
        btnMinus = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        txtAmount = new javax.swing.JTextField();
        lblProdutName = new javax.swing.JLabel();
        pnlBlackLine = new javax.swing.JPanel();
        lblMenuType = new javax.swing.JLabel();
        lblBackgroundPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlBackground.setLayout(null);

        lblPath.setBackground(new java.awt.Color(255, 255, 0));
        lblPath.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblPath.setForeground(new java.awt.Color(255, 255, 102));
        lblPath.setText("MENU > MAXI TEAS >");
        pnlBackground.add(lblPath);
        lblPath.setBounds(450, 20, 240, 29);

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/EKS.png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        pnlBackground.add(lblExit);
        lblExit.setBounds(900, 20, 70, 60);

        btnOrder.setBackground(new java.awt.Color(226, 176, 1));
        btnOrder.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnOrder.setText("ORDER THIS DRINK");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        pnlBackground.add(btnOrder);
        btnOrder.setBounds(380, 580, 290, 50);

        lblProductPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Cacao.png"))); // NOI18N
        pnlBackground.add(lblProductPic);
        lblProductPic.setBounds(350, 150, 330, 380);

        lblAmount.setFont(new java.awt.Font("Bahnschrift", 1, 35)); // NOI18N
        lblAmount.setText("AMOUNT");
        pnlBackground.add(lblAmount);
        lblAmount.setBounds(750, 470, 190, 40);

        lblQuantity.setFont(new java.awt.Font("Bahnschrift", 1, 35)); // NOI18N
        lblQuantity.setText("QUANTITY");
        pnlBackground.add(lblQuantity);
        lblQuantity.setBounds(740, 330, 210, 50);

        lblPrizeSize.setFont(new java.awt.Font("Bahnschrift", 1, 35)); // NOI18N
        lblPrizeSize.setText("PRICE & SIZE");
        pnlBackground.add(lblPrizeSize);
        lblPrizeSize.setBounds(710, 130, 250, 40);

        txtSpecialInstruct.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtSpecialInstruct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSpecialInstruct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 160, 7), 5));
        txtSpecialInstruct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialInstructActionPerformed(evt);
            }
        });
        pnlBackground.add(txtSpecialInstruct);
        txtSpecialInstruct.setBounds(20, 490, 330, 140);

        lblAddRider.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        lblAddRider.setText("ADD RIDER?");
        pnlBackground.add(lblAddRider);
        lblAddRider.setBounds(20, 110, 330, 40);

        btnMinusBoba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Minus.png"))); // NOI18N
        btnMinusBoba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusBobaMouseClicked(evt);
            }
        });
        pnlBackground.add(btnMinusBoba);
        btnMinusBoba.setBounds(200, 160, 40, 40);

        txtQuantityBoba.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        txtQuantityBoba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        txtQuantityBoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityBobaActionPerformed(evt);
            }
        });
        pnlBackground.add(txtQuantityBoba);
        txtQuantityBoba.setBounds(250, 160, 40, 40);

        btnPlusBoba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Plus.png"))); // NOI18N
        btnPlusBoba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusBobaMouseClicked(evt);
            }
        });
        pnlBackground.add(btnPlusBoba);
        btnPlusBoba.setBounds(300, 160, 40, 40);

        btnMinusNata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Minus.png"))); // NOI18N
        btnMinusNata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusNataMouseClicked(evt);
            }
        });
        pnlBackground.add(btnMinusNata);
        btnMinusNata.setBounds(200, 220, 40, 40);

        outofstock_500ml.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        outofstock_500ml.setText("500 ML cups are out of stock!");
        pnlBackground.add(outofstock_500ml);
        outofstock_500ml.setBounds(710, 190, 240, 22);

        outofstock_700ml.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        outofstock_700ml.setText("700 ML cups are out of stock!");
        pnlBackground.add(outofstock_700ml);
        outofstock_700ml.setBounds(710, 260, 240, 22);

        txtQuantityNata.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        txtQuantityNata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        txtQuantityNata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityNataActionPerformed(evt);
            }
        });
        pnlBackground.add(txtQuantityNata);
        txtQuantityNata.setBounds(250, 220, 40, 40);

        btnPlusNata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Plus.png"))); // NOI18N
        btnPlusNata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusNataMouseClicked(evt);
            }
        });
        pnlBackground.add(btnPlusNata);
        btnPlusNata.setBounds(300, 220, 40, 40);

        btnMinusPop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Minus.png"))); // NOI18N
        btnMinusPop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusPopMouseClicked(evt);
            }
        });
        pnlBackground.add(btnMinusPop);
        btnMinusPop.setBounds(200, 280, 40, 40);

        txtQuantityPop.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        txtQuantityPop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        txtQuantityPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityPopActionPerformed(evt);
            }
        });
        pnlBackground.add(txtQuantityPop);
        txtQuantityPop.setBounds(250, 280, 40, 40);

        btnPlusPop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Plus.png"))); // NOI18N
        btnPlusPop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusPopMouseClicked(evt);
            }
        });
        pnlBackground.add(btnPlusPop);
        btnPlusPop.setBounds(300, 280, 40, 40);

        btnMinusFruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Minus.png"))); // NOI18N
        btnMinusFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusFruitMouseClicked(evt);
            }
        });
        pnlBackground.add(btnMinusFruit);
        btnMinusFruit.setBounds(200, 340, 40, 40);

        txtQuantityFruit.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        txtQuantityFruit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        txtQuantityFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityFruitActionPerformed(evt);
            }
        });
        pnlBackground.add(txtQuantityFruit);
        txtQuantityFruit.setBounds(250, 340, 40, 40);

        btnPlusFruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Plus.png"))); // NOI18N
        btnPlusFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusFruitMouseClicked(evt);
            }
        });
        pnlBackground.add(btnPlusFruit);
        btnPlusFruit.setBounds(300, 340, 40, 40);

        btnMinusFoam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Minus.png"))); // NOI18N
        btnMinusFoam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusFoamMouseClicked(evt);
            }
        });
        pnlBackground.add(btnMinusFoam);
        btnMinusFoam.setBounds(200, 400, 40, 40);

        txtQuantityFoam.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        txtQuantityFoam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        txtQuantityFoam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityFoamActionPerformed(evt);
            }
        });
        pnlBackground.add(txtQuantityFoam);
        txtQuantityFoam.setBounds(250, 400, 40, 40);

        btnPlusFoam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Plus.png"))); // NOI18N
        btnPlusFoam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusFoamMouseClicked(evt);
            }
        });
        pnlBackground.add(btnPlusFoam);
        btnPlusFoam.setBounds(300, 400, 40, 40);

        togbtn500.setBackground(new java.awt.Color(255, 204, 0));
        togbtn500.setFont(new java.awt.Font("Bahnschrift", 1, 29)); // NOI18N
        togbtn500.setForeground(new java.awt.Color(255, 255, 255));
        togbtn500.setText("₱89 | 500 ML");
        togbtn500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                togbtn500MouseClicked(evt);
            }
        });
        pnlBackground.add(togbtn500);
        togbtn500.setBounds(710, 180, 230, 50);

        lblSpecialInstruct1.setFont(new java.awt.Font("Bahnschrift", 1, 27)); // NOI18N
        lblSpecialInstruct1.setText("SPECIAL INSTRUCTIONS:");
        pnlBackground.add(lblSpecialInstruct1);
        lblSpecialInstruct1.setBounds(20, 450, 330, 30);

        togbtn700.setBackground(new java.awt.Color(255, 204, 0));
        togbtn700.setFont(new java.awt.Font("Bahnschrift", 1, 29)); // NOI18N
        togbtn700.setForeground(new java.awt.Color(255, 255, 255));
        togbtn700.setText("₱99 | 700 ML");
        togbtn700.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                togbtn700MouseClicked(evt);
            }
        });
        pnlBackground.add(togbtn700);
        togbtn700.setBounds(710, 240, 230, 50);

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Minus.png"))); // NOI18N
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusMouseClicked(evt);
            }
        });
        pnlBackground.add(btnMinus);
        btnMinus.setBounds(720, 390, 60, 40);

        txtQuantity.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        txtQuantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        pnlBackground.add(txtQuantity);
        txtQuantity.setBounds(790, 390, 80, 40);

        btnPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Plus.png"))); // NOI18N
        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusMouseClicked(evt);
            }
        });
        pnlBackground.add(btnPlus);
        btnPlus.setBounds(880, 390, 60, 40);

        txtAmount.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        txtAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        pnlBackground.add(txtAmount);
        txtAmount.setBounds(710, 520, 240, 40);

        lblProdutName.setFont(new java.awt.Font("Bahnschrift", 0, 37)); // NOI18N
        lblProdutName.setText("Cacao");
        pnlBackground.add(lblProdutName);
        lblProdutName.setBounds(450, 30, 320, 60);

        pnlBlackLine.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlBlackLineLayout = new javax.swing.GroupLayout(pnlBlackLine);
        pnlBlackLine.setLayout(pnlBlackLineLayout);
        pnlBlackLineLayout.setHorizontalGroup(
            pnlBlackLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBlackLineLayout.setVerticalGroup(
            pnlBlackLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnlBackground.add(pnlBlackLine);
        pnlBlackLine.setBounds(440, 20, 5, 60);

        lblMenuType.setFont(new java.awt.Font("Angeline Vintage", 1, 75)); // NOI18N
        lblMenuType.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/Maxi Tea.png"))); // NOI18N
        pnlBackground.add(lblMenuType);
        lblMenuType.setBounds(60, 0, 390, 120);

        lblBackgroundPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/00.jpg"))); // NOI18N
        pnlBackground.add(lblBackgroundPic);
        lblBackgroundPic.setBounds(0, 0, 970, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSpecialInstructActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialInstructActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialInstructActionPerformed
public void cups500(){
        try {

                 pst3 = con.prepareStatement("select ITEM_QTY from supplies where ITEM_CODE = ?");
		 pst3.setString(1,"CUPS500");
		 rs2 = pst3.executeQuery();

            
            
            	 while(rs2.next())
            	{       
                        
                            int currentQty = Integer.parseInt(rs2.getString("ITEM_QTY"));
                            
                            int ctr_qty = POSNEW.qty_cups500;
                            int ctr1= POSNEW.ctr_cups500;
                            
                            
                            if(ctr1 != 0){
                                
                            if (ctr_qty == 0){
                            togbtn500.setVisible(false);
                            outofstock_500ml.setVisible(true);

                        }
                        else{
                            togbtn500.setVisible(true);
                            outofstock_500ml.setVisible(false);

                        }
                            }
                        
                            else if (ctr1 == 0){
                        
               		  if (currentQty == 0){
                            togbtn500.setVisible(false);
                            outofstock_500ml.setVisible(true);
                             POSNEW.ctr_cups500 = POSNEW.ctr_cups500  +1;
                        }
                        else{
                            togbtn500.setVisible(true);
                            outofstock_500ml.setVisible(false);

                        }
                       
                }
               
                }

    
            
        }catch (SQLException ex) {
            Logger.getLogger(MaxCOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void plus_500(){
    
    try {

                 pst3 = con.prepareStatement("select ITEM_QTY from supplies where ITEM_CODE = ?");
		 pst3.setString(1,"CUPS500");
		 rs2 = pst3.executeQuery();

            
            
            	 if(rs2.next())
            	{
   
               		int currentQty500 = Integer.parseInt(rs2.getString("ITEM_QTY"));
                        int ctr_qty = POSNEW.qty_cups500;
                        int currentAmt = Integer.parseInt(txtQuantity.getText());
                        int ctr1= POSNEW.ctr_cups500;

               
                        
                         if(ctr1 != 0){
                            
                            if( ctr_qty== currentAmt){
   
                                    btnPlus.setVisible(false);
                                
                                
                            }
                            else{
                                btnPlus.setVisible(true);
                            }
                        
                         }
                         else if (ctr1 == 0){
                             POSNEW.qty_cups500 = currentQty500;
                                 POSNEW.ctr_cups500 = POSNEW.ctr_cups500 +1;
                             if( currentQty500== currentAmt){

                                btnPlus.setVisible(false);
                                
                            }
                            else{
                                btnPlus.setVisible(true);
                            }
                         }
                         
                        
         
               }
          

    
            
        }catch (SQLException ex) {
            Logger.getLogger(MaxCOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
}

public void plus_700(){
    
  try {

                 pst3 = con.prepareStatement("select ITEM_QTY from supplies where ITEM_CODE = ?");
		 pst3.setString(1,"CUPS700");
		 rs2 = pst3.executeQuery();

            
            
            	 if(rs2.next())
            	{
   
               		int currentQty700 = Integer.parseInt(rs2.getString("ITEM_QTY"));
                        int ctr_qty = POSNEW.qty_cups700;
                        int currentAmt = Integer.parseInt(txtQuantity.getText());
                        int ctr1= POSNEW.ctr_cups700;
                        
                         if(ctr1 != 0){
                            
                            if( ctr_qty== currentAmt){
   
                                    btnPlus.setVisible(false);
                                
                                
                            }
                            else{
                                btnPlus.setVisible(true);
                            }
                        
                         }
                         else if (ctr1 == 0){
                             POSNEW.qty_cups700 = currentQty700;
                                 POSNEW.ctr_cups700 = POSNEW.ctr_cups700 +1;
                             if( currentQty700== currentAmt){

                                btnPlus.setVisible(false);
                                
                            }
                            else{
                                btnPlus.setVisible(true);
                            }
                         }
                         
                        
         
               }
          

    
            
        }catch (SQLException ex) {
            Logger.getLogger(MaxCOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
}

public void cups700(){
     try {

                 pst3 = con.prepareStatement("select ITEM_QTY from supplies where ITEM_CODE = ?");
		 pst3.setString(1,"CUPS700");
		 rs2 = pst3.executeQuery();

            
            
            	 while(rs2.next())
            	{       
                        
                            int currentQty = Integer.parseInt(rs2.getString("ITEM_QTY"));
                            
                            int ctr_qty = POSNEW.qty_cups700;
                            int ctr1= POSNEW.ctr_cups700;
                            
                            
                            if(ctr1 != 0){
                                
                            if (ctr_qty == 0){
                            togbtn700.setVisible(false);
                            outofstock_700ml.setVisible(true);

                        }
                        else{
                            togbtn700.setVisible(true);
                            outofstock_700ml.setVisible(false);

                        }
                            }
                        
                            else if (ctr1 == 0){
                        
               		  if (currentQty == 0){
                            togbtn700.setVisible(false);
                            outofstock_700ml.setVisible(true);
                             POSNEW.ctr_cups700 = POSNEW.ctr_cups700  +1;
                        }
                        else{
                            togbtn700.setVisible(true);
                            outofstock_700ml.setVisible(false);

                        }
                       
                }
               
                }

    
            
        }catch (SQLException ex) {
            Logger.getLogger(MaxCOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        String date_ordered = POSNEW.lblDate.getText();
        String amount = txtAmount.getText();
        float floatAmt = Float.parseFloat(amount);
        String qty = txtQuantity.getText();
        int intQty = Integer.parseInt(qty);
        String special1 = txtSpecialInstruct.getText();
        String num = POSNEW.lblRecNo.getText();
        int intNum = Integer.parseInt(num);
       
        if (togbtn500.isSelected()==false && togbtn700.isSelected()==false){
           new Size().setVisible(true);
       }
       
       
       else {
        Connect();
        try {
           
            pst = con.prepareStatement("insert into customer(Record_num,Qty,Prod_Code,Item_Code, Prod_Name,Date,Amt,Instructions)values(?,?,?,?,?,?,?,?)");
            if (togbtn500.isSelected()){
           
            pst.setInt(1, intNum);
            pst.setInt(2, intQty);
            pst.setString(3, "MAXICACAOD500");
            pst.setString(4, "CUPS500");
            pst.setString(5, "Cacao (500 ml)");
            pst.setString(6, date_ordered);
            pst.setFloat(7, floatAmt);
            pst.setString(8, special1);
            POSNEW.qty_cups500 = POSNEW.qty_cups500 - intQty;
            }
            
            else if (togbtn700.isSelected()){
            pst.setInt(1, intNum);
            pst.setInt(2, intQty);
            pst.setString(3, "MAXICACAOD700");
            pst.setString(4, "CUPS700");
            pst.setString(5, "Cacao (700 ml)");
            pst.setString(6, date_ordered);
            pst.setFloat(7, floatAmt);
            pst.setString(8, special1);
            POSNEW.qty_cups700 = POSNEW.qty_cups700 - intQty;
            }
           pst.executeUpdate();
          
            int currentNo = Integer.parseInt(POSNEW.lblRecNo.getText());
    
  
         int newNo = (int) (currentNo+1);
         String newNoGet = String.valueOf(newNo);
         POSNEW.lblRecNo.setText(newNoGet);
         
         String OldTotal = POSNEW.lblTotal.getText();
         String NewTotal = this.txtAmount.getText();
         float old = Float.parseFloat(OldTotal);
         float new1 = Float.parseFloat(NewTotal);
         float new2 = (old+new1);
         String new2Get = String.valueOf(new2);
         POSNEW.lblTotal.setText(new2Get);
         
         POSNEW.refresh_ctr = POSNEW.refresh_ctr + 1;
         POSNEW.btnRefresh.setEnabled(true);
         POSNEW.btnConfirm.setEnabled(false);
         
          float currentDiscount1 = Float.parseFloat(POSNEW.lblAppliedDiscount.getText());
        float finalTotal1 = (float) (new2 - currentDiscount1);
        String fintot1Get = String.valueOf(finalTotal1);
        POSNEW.lblPaymentAmount.setText(fintot1Get);
        
        if (POSNEW.rdbtnSenior.isSelected()== true || POSNEW.rdbtnPWD.isSelected()== true)
         {
            
            float new4 = (float) (new2 * 0.20);
            String new4Get = String.valueOf(new4);
            POSNEW.lblAppliedDiscount.setText(new4Get);

            float finalTotal = (float) (new2 - new4);
            String fintotGet = String.valueOf(finalTotal);
            POSNEW.lblPaymentAmount.setText(fintotGet);
         }
         
         this.setVisible(false);

            
        } catch (SQLException ex) {
            Logger.getLogger(MaxCOrdering.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void btnMinusBobaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusBobaMouseClicked
        if (intQuantityBoba > 0) {
            fltAmount-=15;
            String strAmount = String.valueOf(fltAmount);
            txtAmount.setText(strAmount);
            intQuantityBoba--;
            String strQuantityBoba = String.valueOf(intQuantityBoba);
            txtQuantityBoba.setText(strQuantityBoba);
            fltPrice = fltAmount * intQuantity;
            String strPrice = String.valueOf(fltPrice);
            txtAmount.setText(strPrice);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnMinusBobaMouseClicked

    private void txtQuantityBobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityBobaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityBobaActionPerformed

    private void btnPlusBobaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusBobaMouseClicked
        fltAmount+=15;
        String strAmount = String.valueOf(fltAmount);
        txtAmount.setText(strAmount);
        intQuantityBoba++;
        String strQuantityBoba = String.valueOf(intQuantityBoba);
        txtQuantityBoba.setText(strQuantityBoba);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice);      // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusBobaMouseClicked

    private void btnMinusNataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusNataMouseClicked
        if (intQuantityNata > 0) {
            fltAmount-=15;
            String strAmount = String.valueOf(fltAmount);
            txtAmount.setText(strAmount);
            intQuantityNata--;
            String strQuantityNata = String.valueOf(intQuantityNata);
            txtQuantityNata.setText(strQuantityNata);
            fltPrice = fltAmount * intQuantity;
            String strPrice = String.valueOf(fltPrice);
            txtAmount.setText(strPrice);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnMinusNataMouseClicked

    private void txtQuantityNataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityNataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityNataActionPerformed

    private void btnPlusNataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusNataMouseClicked
        fltAmount+=15;
        String strAmount = String.valueOf(fltAmount);
        txtAmount.setText(strAmount);
        intQuantityNata++;
        String strQuantityNata = String.valueOf(intQuantityNata);
        txtQuantityNata.setText(strQuantityNata);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice);// TODO add your handling code here:
    }//GEN-LAST:event_btnPlusNataMouseClicked

    private void btnMinusPopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusPopMouseClicked
        if (intQuantityPop > 0) {
            fltAmount-=15;
            String strAmount = String.valueOf(fltAmount);
            txtAmount.setText(strAmount);
            intQuantityPop--;
            String strQuantityPop = String.valueOf(intQuantityPop);
            txtQuantityPop.setText(strQuantityPop);
            fltPrice = fltAmount * intQuantity;
            String strPrice = String.valueOf(fltPrice);
            txtAmount.setText(strPrice);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnMinusPopMouseClicked

    private void txtQuantityPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityPopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityPopActionPerformed

    private void btnPlusPopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusPopMouseClicked
        fltAmount+=15;
        String strAmount = String.valueOf(fltAmount);
        txtAmount.setText(strAmount);
        intQuantityPop++;
        String strQuantityPop = String.valueOf(intQuantityPop);
        txtQuantityPop.setText(strQuantityPop);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice);// TODO add your handling code here:
    }//GEN-LAST:event_btnPlusPopMouseClicked

    private void btnMinusFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusFruitMouseClicked
        if (intQuantityFruit > 0) {
            fltAmount-=15;
            String strAmount = String.valueOf(fltAmount);
            txtAmount.setText(strAmount);
            intQuantityFruit--;
            String strQuantityFruit = String.valueOf(intQuantityFruit);
            txtQuantityFruit.setText(strQuantityFruit);
            fltPrice = fltAmount * intQuantity;
            String strPrice = String.valueOf(fltPrice);
            txtAmount.setText(strPrice);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnMinusFruitMouseClicked

    private void txtQuantityFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityFruitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityFruitActionPerformed

    private void btnPlusFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusFruitMouseClicked
        fltAmount+=15;
        String strAmount = String.valueOf(fltAmount);
        txtAmount.setText(strAmount);
        intQuantityFruit++;
        String strQuantityFruit = String.valueOf(intQuantityFruit);
        txtQuantityFruit.setText(strQuantityFruit);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice);// TODO add your handling code here:
    }//GEN-LAST:event_btnPlusFruitMouseClicked

    private void btnMinusFoamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusFoamMouseClicked
        if (intQuantityFoam > 0) {
            fltAmount-=25;
            String strAmount = String.valueOf(fltAmount);
            txtAmount.setText(strAmount);
            intQuantityFoam--;
            String strQuantityFoam = String.valueOf(intQuantityFoam);
            txtQuantityFoam.setText(strQuantityFoam);
            fltPrice = fltAmount * intQuantity;
            String strPrice = String.valueOf(fltPrice);
            txtAmount.setText(strPrice);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnMinusFoamMouseClicked

    private void txtQuantityFoamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityFoamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityFoamActionPerformed

    private void btnPlusFoamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusFoamMouseClicked
        fltAmount+=25;
        String strAmount = String.valueOf(fltAmount);
        txtAmount.setText(strAmount);
        intQuantityFoam++;
        String strQuantityFoam = String.valueOf(intQuantityFoam);
        txtQuantityFoam.setText(strQuantityFoam);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice);// TODO add your handling code here:
    }//GEN-LAST:event_btnPlusFoamMouseClicked

    private void togbtn500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_togbtn500MouseClicked
        if(togbtn500.isSelected()){
          fltAmount+=89; 
          togbtn700.setVisible(false);
          plus_500();
             txtQuantity.setText("1");  
             intQuantity = 1;
        }
        

        else{
            fltAmount-=89;
            btnPlus.setVisible(true);
            
            if(outofstock_700ml.isVisible()){
                
                togbtn700.setVisible(false);
            }
            else{
                togbtn700.setVisible(true);
            }
        }

        String strAmount = String.valueOf(fltAmount);
        txtAmount.setText(strAmount);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice);// TODO add your handling code here:
    }//GEN-LAST:event_togbtn500MouseClicked

    private void togbtn700MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_togbtn700MouseClicked
        if(togbtn700.isSelected()){
        fltAmount+=99;
        togbtn500.setVisible(false);
        plus_700();
          txtQuantity.setText("1");  
          intQuantity = 1;
        }
        else{
        fltAmount-=99;
        btnPlus.setVisible(true);
        if(outofstock_500ml.isVisible()){
                
                togbtn500.setVisible(false);
            }
            else{
                togbtn500.setVisible(true);
            }
        }

        String strAmount = String.valueOf(fltAmount);
        txtAmount.setText(strAmount);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice);// TODO add your handling code here:
    }//GEN-LAST:event_togbtn700MouseClicked

    private void btnMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseClicked
        if (intQuantity > 1) {
            intQuantity--;
            String strQuantity = String.valueOf(intQuantity);
            txtQuantity.setText(strQuantity);
            fltPrice = fltAmount * intQuantity;
            String strPrice = String.valueOf(fltPrice);
            txtAmount.setText(strPrice);
            
            if (togbtn500.isSelected()){
                plus_500();
            }
            else if (togbtn700.isSelected()){
                plus_700();
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnMinusMouseClicked

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMouseClicked
        intQuantity++;
        String strQuantity = String.valueOf(intQuantity);
        txtQuantity.setText(strQuantity);
        fltPrice = fltAmount * intQuantity;
        String strPrice = String.valueOf(fltPrice);
        txtAmount.setText(strPrice); 

        if (togbtn500.isSelected()){
                plus_500();
            }
            else if (togbtn700.isSelected()){
                plus_700();
            }// TODO add your handling code here:
    }//GEN-LAST:event_btnPlusMouseClicked

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaxCOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaxCOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaxCOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaxCOrdering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaxCOrdering().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMinusBoba;
    private javax.swing.JButton btnMinusFoam;
    private javax.swing.JButton btnMinusFruit;
    private javax.swing.JButton btnMinusNata;
    private javax.swing.JButton btnMinusPop;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlusBoba;
    private javax.swing.JButton btnPlusFoam;
    private javax.swing.JButton btnPlusFruit;
    private javax.swing.JButton btnPlusNata;
    private javax.swing.JButton btnPlusPop;
    private javax.swing.JLabel lblAddRider;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBackgroundPic;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMenuType;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblPrizeSize;
    private javax.swing.JLabel lblProductPic;
    private javax.swing.JLabel lblProdutName;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblSpecialInstruct1;
    private javax.swing.JLabel outofstock_500ml;
    private javax.swing.JLabel outofstock_700ml;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBlackLine;
    private javax.swing.JToggleButton togbtn500;
    private javax.swing.JToggleButton togbtn700;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantityBoba;
    private javax.swing.JTextField txtQuantityFoam;
    private javax.swing.JTextField txtQuantityFruit;
    private javax.swing.JTextField txtQuantityNata;
    private javax.swing.JTextField txtQuantityPop;
    private javax.swing.JTextField txtSpecialInstruct;
    // End of variables declaration//GEN-END:variables
}
