package orderingsystem;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rejean
 */
public class Verify extends javax.swing.JFrame {

    /** Creates new form VERIFY2 */
    public Verify() {
        initComponents();

        this.setSize(530, 424);
     
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        txtfldAnswer = new javax.swing.JTextField();
        lblAnswer = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        cmboxQuestions = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lblClose.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblClose);
        lblClose.setBounds(490, 0, 280, 60);

        lblConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/CONFIRM ID.png"))); // NOI18N
        lblConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmMouseClicked(evt);
            }
        });
        getContentPane().add(lblConfirm);
        lblConfirm.setBounds(130, 320, 230, 70);

        txtfldAnswer.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        getContentPane().add(txtfldAnswer);
        txtfldAnswer.setBounds(160, 220, 340, 40);

        lblAnswer.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(255, 255, 255));
        lblAnswer.setText("ANSWER:");
        getContentPane().add(lblAnswer);
        lblAnswer.setBounds(10, 210, 160, 60);

        lblQuestion.setFont(new java.awt.Font("Bahnschrift", 1, 20)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion.setText("QUESTION:");
        getContentPane().add(lblQuestion);
        lblQuestion.setBounds(10, 140, 160, 60);

        cmboxQuestions.setBackground(new java.awt.Color(255, 240, 0));
        cmboxQuestions.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cmboxQuestions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On what date did SUNTEA start its operations?", "Name SUNTEA's bestselling drink in 2019.", "Who made up the business name?" }));
        getContentPane().add(cmboxQuestions);
        cmboxQuestions.setBounds(160, 150, 340, 40);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderingsystem/VERIFY 5.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 535, 424);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmMouseClicked
        String question = (String)cmboxQuestions.getSelectedItem();

        String ans = txtfldAnswer.getText();
        if (question.equals("On what date did SUNTEA start its operations?"))
        {
            if(ans.equals("")){
                new AllFieldsRequire().setVisible(true);
            }
            if (ans.equals("May 10, 2018"))
            {
                dispose();
                new ForgotPassword().setVisible(true);
            }
            else if (!ans.equals("May 10, 2018") && !ans.equals(""))
            {

                new IncorrectAnswer().setVisible(true);
                txtfldAnswer.setText("");

            }
        }

        if (question.equals("Name SUNTEA's bestselling drink in 2019."))
        {
            if(ans.equals("")){
                new AllFieldsRequire().setVisible(true);
            }
            if (ans.equals("Nutella Addiction"))
            {
                dispose();
                new ForgotPassword().setVisible(true);
            }
            else if (!ans.equals("Nutella Addiction") && !ans.equals("") )
            {
                new IncorrectAnswer().setVisible(true);
                txtfldAnswer.setText("");
            }
        }
        if (question.equals("Who made up the business name?"))
        {
            if(ans.equals("")){
                new AllFieldsRequire().setVisible(true);
            }
            if (ans.equals("John Paul Calamba") || ans.equals("Jurgen Vega"))
            {
                dispose();
                new ForgotPassword().setVisible(true);
            }
            else if(!ans.equals("John Paul Calamba") && !ans.equals(""))
            {
                new IncorrectAnswer().setVisible(true);
                txtfldAnswer.setText("");
            }
            
             else if(!ans.equals("Jurgen Vega") && !ans.equals(""))
            {
                new IncorrectAnswer().setVisible(true);
                txtfldAnswer.setText("");
            }
        }
    }//GEN-LAST:event_lblConfirmMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        new Choose().setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Verify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmboxQuestions;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JTextField txtfldAnswer;
    // End of variables declaration//GEN-END:variables

}
